version: "3"


volumes:
    sql:
      driver: local
      driver_opts:
        type: nfs
        o: addr=192.168.200.200,rw,vers=4
        device: ":/opt/${CLIENT}_SQL"
    html:
      driver: local
      driver_opts:
        type: nfs
        o: addr=192.168.200.200,rw,vers=4
        device: ":/opt/${CLIENT}_HTML"
    moodle:
      driver: local
      driver_opts:
        type: nfs
        o: addr=192.168.200.200,rw,vers=4
        device: ":/opt/${CLIENT}_MOODLE"

networks:
  external:
    external: true


services:
  mysql:
    image: mysql/mysql-server:5.7
    expose:
      - "3306"
    volumes:
      - sql:/var/lib/mysql:Z
      - ./my.cnf:/etc/my.cnf:Z
    environment:
      - MYSQL_ROOT_PASSWORD="${CLIENT}12345"
      - MYSQL_ROOT_HOST=a%
      - LANG=pl_PL.UTF-8
  php-fpm:
    image: mdsmart/moodle_php-fpm
    volumes:
      - html:/var/www:Z
      - moodle:/var/moodledata:Z
    depends_on:
      - mysql
  nginx:
    image: mdsmart/moodle_nginx
    depends_on: 
      - php-fpm
    expose:
      - "80"
    volumes:
      - html:/var/www:Z
      - moodle:/var/moodledata:Z
    deploy:
      labels:
        - traefik.enable: true
        - traefik.port: 80
        - traefik.backend: ${CLIENT}
        - traefik.webservice.frontend.entryPoints: http
        - traefik.docker.network: external
        - traefik.passHostHeader: true
        - traefik.frontend.rule: Host:"${CLIENT}.se.emdo.pro"


# vim:ts=2:sw=2:et:ai:
