version: "3.2"


volumes:
    vol_moodle:
      driver: local
      driver_opts:
        o: bind
        type: none
        device: /opt/${CLIENT}/moodle
    vol_html:
      driver: local
      driver_opts:
        o: bind
        type: none
        device: /opt/${CLIENT}/html

    vol_mysql:
      driver: local
      driver_opts:
        o: bind
        type: none
        device: /opt/${CLIENT}/mysql

networks:
  external:
    external: true

services:
  
  mysql:
    image: mdsmart/mysql:5.7
    expose:
      - "3306"
    volumes:
      - vol_mysql:/var/lib/mysql:Z
    environment:
      - MYSQL_ROOT_PASSWORD=${CLIENT}12345
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=${CLIENT}
      - MYSQL_USER=${CLIENT}
      - MYSQL_PASSWORD=${CLIENT}12345
      - LANG=pl_PL.UTF-8
    healthcheck:
      disable: true
  
  php-fpm:
    image: mdsmart/moodle_php-fpm
    volumes:
      - vol_html:/var/www:Z
      - vol_moodle:/var/moodledata:Z
    depends_on:
      - mysql
    environment:
      - FTPPASS=ZmienMnie1
      - DBPASS=${CLIENT}12345
      - DBUSER=${CLIENT}
      - DBNAME=${CLIENT}
  
  nginx:
    image: mdsmart/moodle_nginx
    depends_on: 
      - php-fpm
    expose:
      - "80"
    volumes:
      - vol_html:/var/www:Z
      - vol_moodle:/var/moodledata:Z
    networks:
      - external
      - default
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.port=80"
        - "traefik.backend=${CLIENT}"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.headers.SSLRedirect=true"
        - "traefik.docker.network=external"
        - "traefik.frontend.rule=Host:${CLIENT}.apps.dolineo.com"
        - "traefik.protocol=http"
        - "traefik.passHostHeader=true"


# vim:ts=2:sw=2:et:ai:
