version: "3.2"


volumes:
    nfs:
      driver: local
      driver_opts:
        type: nfs
        o: addr=192.168.200.200,rw,vers=4
        device: ":/opt/${CLIENT}"

networks:
  external:
    external: true


services:
  mysql:
    image: mysql/mysql-server:5.7
    expose:
      - "3306"
    volumes:
      - nfs:/var/lib/mysql:Z
      - ./my.cnf:/etc/my.cnf:Z
    environment:
      - MYSQL_ROOT_PASSWORD="${CLIENT}12345"
      - MYSQL_ROOT_HOST=%
      - LANG=pl_PL.UTF-8
  php-fpm:
    image: mdsmart/moodle_php-fpm
    volumes:
      - nfs:/var/www:Z
      - nfs:/var/moodledata:Z
    depends_on:
      - mysql
  nginx:
    image: mdsmart/moodle_nginx
    depends_on: 
      - php-fpm
    expose:
      - "80"
    volumes:
      - nfs:/var/www:Z
      - nfs:/var/moodledata:Z
    deploy:
      labels:
        - traefik.enable="true"
        - traefik.port="80"
        - traefik.backend="${CLIENT}"
        - traefik.webservice.frontend.entryPoints="http"
        - traefik.docker.network="external"
        - traefik.passHostHeader="true"
        - traefik.frontend.rule="Host:${CLIENT}.poc.dolineo.pl"


# vim:ts=2:sw=2:et:ai:
